apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubestellar-applications
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/part-of: lab
spec:
  project: default
  source:
    repoURL: https://github.com/projectbluefin/lab
    targetRevision: main
    path: argocd
    directory:
      include: "{kubestellar-postgres-app.yaml,kubestellar-app.yaml,kubestellar-console-app.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
