apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubestellar-observability
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "50"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubestellar-observability
  annotations:
    argocd.argoproj.io/sync-wave: "50"
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - services
      - services/proxy
      - pods
      - pods/log
      - nodes
    verbs: [get, list]
  - apiGroups: [metrics.k8s.io]
    resources:
      - nodes
      - pods
    verbs: [get, list]
  - apiGroups: [apps]
    resources:
      - deployments
      - daemonsets
    verbs: [get, list]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [clusterroles]
    verbs: [get]
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get]
  - apiGroups: [tenancy.kflex.kubestellar.org]
    resources: [controlplanes]
    verbs: [get, list]
  - apiGroups: [cluster.open-cluster-management.io]
    resources: [managedclusters]
    verbs: [get, list]
  - apiGroups: [work.open-cluster-management.io]
    resources: [manifestworks]
    verbs: [get, list]
  - apiGroups: [control.kubestellar.io]
    resources: [workstatuses]
    verbs: [get, list]
  - apiGroups: [addon.open-cluster-management.io]
    resources: [managedclusteraddons]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubestellar-observability
  annotations:
    argocd.argoproj.io/sync-wave: "50"
subjects:
  - kind: ServiceAccount
    name: kubestellar-observability
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubestellar-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubestellar-observability-executor
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "50"
subjects:
  - kind: ServiceAccount
    name: kubestellar-observability
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-default-executor
